name = "CrystalGraphConvNet"
uuid = "249d146e-a97e-448b-a8b4-4f18998c9c99"
version = "0.1.0"
authors = ["singularitti <singularitti@outlook.com> and contributors"]

[deps]
CrystallographyBase = "93b1d1cd-a8ea-4aa5-adb1-b2407ea0ba8d"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CrystallographyBase = "0.14.3"
Lux = "1.27.1"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
